### ISSUE TITLE
Cannot serialize a SimpleLazyObject

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/django-argonauts#15]
In my template I'm trying to pass the `csrf_token` to JavaScript using the `|json` filter. This worked previously on Django 1.6, however, it seems that in Django 1.8 the `csrf_token` has become lazy. I wonder if there are similar issues with request.user being a lazy user?

Traceback:

```
Traceback (most recent call last):
  File "/XXX/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/XXX/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/XXX/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/XXX/lib/python2.7/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/XXX/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/XXX/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/XXX/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/XXX/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/XXX/lib/python2.7/site-packages/django_jinja/backend.py", line 105, in render
    return self.template.render(context)
  File "/XXX/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/XXX/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  # ...
    var CSRF_TOKEN = {{ csrf_token|json }};
  File "/XXX/lib/python2.7/site-packages/argonauts/templatetags/argonauts.py", line 23, in json
    json_str = json_dumps(a)
  File "/XXX/lib/python2.7/site-packages/argonauts/__init__.py", line 29, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 201, in encode
    return encode_basestring_ascii(o)
TypeError: first argument must be a string, not SimpleLazyObject
```

**Comment by gavinwahl** [comment]
Project has been deprecated
